name: erpnext-hrms
services:
    postgres:
      image: postgres:13-alpine
      environment:
        - POSTGRES_USER=erpnext-hrms
        - POSTGRES_PASSWORD=101medialab
        - POSTGRES_DB=erpnext-hrms
      volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: