name: erpnext-hrms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 101medialab
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      my_network:

  redis:
    image: redis:alpine
    networks:
      my_network:

  frappe:
    build: .
    environment:
      - SITE_NAME=${SITE_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - INTERMEDIATE_DB_USERNAME=${INTERMEDIATE_DB_USERNAME}
      - INTERMEDIATE_DB_PASSWORD=${INTERMEDIATE_DB_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - .:/workspace
#      - ./../:/home/frappe/frappe-bench/apps/erpnext_hrms_addons
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      my_network:
        ipv4_address: 172.19.0.4
    entrypoint: [ "/bin/bash", "/workspace/hrms_setup_mariadb.sh" ]

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  mariadb-data:
